config/routes.rb
Debater::Application.routes.draw do
  resources :topics do
    resources :comments
    resources :topic_user_supports
    member do
      get "vote"
    end
  end
  
    
  
  
  resources :home do
      get :autocomplete_tag_name, :on => :collection
  end

  get "home/index"
  devise_for :users, :controllers => {
      omniauth_callbacks: "users/omniauth_callbacks"
  }
  
  
  devise_scope :user do
    resources :comments
    resources :topic_user_supports
    get "sign_in", :to => "devise/sessions#new"
    get 'logins/sign_out' => 'devise/sessions#destroy'
    get 'logins/edit' => 'devise/registrations#edit', :as => 'edit_login_registration'
    put 'logins' => 'devise/registrations#update', :as => 'login_registration'
  end

  root :to => 'home#index'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  
  has_many :topic_user_supports
  
  has_many :comments
  
  validates :user_id, presence: true
  # ensure that title is present and at least 10 chars long
  validates :question, length: { minimum: 10 }, presence: true
end

app/models/topic_user_support.rb
class TopicUserSupport < ActiveRecord::Base
  belongs_to :users
  belongs_to :topic
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  has_many :topics
  has_many :comments
  
  
  has_many :topic_user_supports
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
         
         def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
             user = User.where(:provider => auth.provider, :uid => auth.uid).first
             if user
               return user
             else
               registered_user = User.where(:email => auth.info.email).first
               if registered_user
                 registered_user.update_attributes(:provider=> auth.provider, :uid=>auth.uid)
                 return registered_user
               else
                 user = User.create( provider:auth.provider,
                                     uid:auth.uid,
                                     email:auth.info.email,
                                     password:Devise.friendly_token[0,20],
                                   )
               end
       
             end
           end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
     @topic = Topic.find(params[:topic_id])
     @comment = @topic.comments.new(params[:comment].permit(:user_id, :body))
     @comment.user_id = current_user.id
     @comment.save
     redirect_to topic_path(@topic)
     
   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @topics = Topic.all
  end
  
  def autocomplete_tag_name
    tags = User.select([:email]).where("name LIKE ?", "%#{params[:name]}%")
        result = tags.collect do |t|
          { value: t.name }
        end
        render json: result
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]

  # GET /topics
  # GET /topics.json
  def index
    @topics = current_user.topics
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @vote =""
    @upcount = @topic.topic_user_supports.where(:support => true).count
    @downcount = @topic.topic_user_supports.where(:support => false).count
    @all_users = @topic.topic_user_supports.select(:user_id).where(:support => true).to_a
    @voters = Array.new
    @all_users.each do |x|
      @voters << x.user_id
    end
    
    @support_comments = @topic.comments.where(:user_id => @voters)
    @against_comments = @topic.comments.where.not(:user_id => @voters)
    
    if !current_user.nil?
      @vote = @topic.topic_user_supports.where(:user_id => current_user.id).first
    end
  end
  
  def vote
    @topic = Topic.find(params[:id])
    @check = @topic.topic_user_supports.where(:user_id=>current_user.id)
    if @check.blank?
      @vote = TopicUserSupport.new(:user_id => current_user.id, :topic_id=>@topic.id, :support => params[:support])
      if params[:support]== "true"
        @cast = "supporting"
      else
        @cast = "against"
      end
        
      respond_to do |format|
        if @vote.save
          if !current_user.uid.blank?
            @fb_user = FbGraph::User.me(session[:fb_access_token].strip)
            @fb_user.feed!(
              :message => "I'm "+@cast+" a topic! Check it out",
              :link => "ec2-54-80-154-0.compute-1.amazonaws.com/topics/"+@topic.id.to_s
            )
          end
          format.html { redirect_to @topic, notice: 'Succesfully voted.' }
          format.json { render action: 'show', status: :created, location: @topic }
        else
          format.html { redirect_to action: 'show' }
          format.json { render json: @vote.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to action: 'show'
    end
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id
    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render action: 'show', status: :created, location: @topic }
      else
        format.html { render action: 'new' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:question, :enable)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
 
    if @user.persisted?
      auth = request.env['omniauth.auth']
      token = auth['credentials']['token']
      session[:fb_access_token] = token
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/comments/_comment.html.erb
								
	                <h5> <% if !comment.user.blank? %>
										<%= comment.user.email %>
										<% end %>
	                    <small><%= comment.created_at %></small>
	                </h5>
									<p><%= comment.body %></p>

app/views/home/index.html.erb
<h1>Hot Debates</h1>

    <% @topics.each do |topic| %>
				<div class="well">
				   <p><%= topic.question %> <small>
						 <% if topic.user.blank? %>
						 <%= "By Anonymous" %>
						 <% else %>
						 <%= "by "+topic.user.email %>
						 <% end %>
					 </small></p>
					<p> <%= topic.topic_user_supports.where(:support => true).count %> debatians are supporting this | <%= topic.topic_user_supports.where(:support => false).count %> debatians are against it </p>
		      <p> <%= link_to 'Show', topic %>
		 			<% if !current_user.nil? && current_user == topic.user %>
		       |<%= link_to 'Edit', edit_topic_path(topic) %>|
		       <%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %> </p>
		 			<% end %>
				</div>
    <% end %>


<br>

<%= link_to 'New Topic', new_topic_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
     
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= link_to 'Debater', root_path, class: 'navbar-brand' %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        
			<% if user_signed_in? %>
			<li><%= link_to "My Topics", topics_path %></li>
			<p class="navbar-text navbar-right">Signed in as <%= current_user.email %></p>
			<li> <%= link_to "Sign out", destroy_user_session_path, :method => 'delete' %> </li>
			<% else %>
			<li><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %></li>
			<li><%= link_to "Sign in", new_user_session_path %></li>
			<% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Debater" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Debater" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
		
  </body>
</html>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_area :question %>
  </div>
  <div class="field">
    <%= f.label :enable %><br>
    <%= f.check_box :enable %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Your Questions</h1>

    <% @topics.each do |topic| %>
				<div class="well">
				   <p><%= topic.question %></p>
		       <%= link_to 'Show', topic %>
		 			<% if !current_user.nil? && current_user == topic.user %>
		       |<%= link_to 'Edit', edit_topic_path(topic) %>|
		       <%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %>
		 			<% end %>
				</div>
    <% end %>

<br>

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<div class="row">
   <div class="col-lg-8">

                <!-- the actual blog post: title/author/date/content -->
                <h1><%= @topic.question %></h1>
                <p class="lead">by 
									<% if @topic.user.nil? %>
									<%= "Anonymous" %>
									<% else %>
									<%= @topic.user.email %>
									<% end %>
                </p>
								<p> <%= @upcount %> debatians are supporting this</p>
								<p> <%= @downcount %> debatians are against it </p>
								
								<% if !@vote.blank? %>
								 <% if @vote.support
								 			@cas = "supporting"
							 			else
											@cas = "against"
										end
								 %>
								<p> You are <%= @cas %> this topic! </p>
								<% end %>
							
                <hr>
								<% if @vote.blank? %>
									<%= link_to "Support it", vote_topic_path(@topic, :support=> "true") , :method => :get, :class =>"btn btn-primary" %>
									<%= link_to "Against it", vote_topic_path(@topic, :support=> "false") , :method => :get, :class =>"btn btn-danger" %>
								<% end %>
									
                <p>
                    <span class="glyphicon glyphicon-time"></span> Posted on <%= @topic.created_at %></p>
                <hr>
                <!-- the comment box -->
								<div class="col-lg-6">
                	<!-- the comments -->
									<h4>Supporters Comments</h4>
									<hr/>
									<% @support_comment = @topic.comments.where(:user_id=>@voters) %>
									<% @support_comment.each do |comment| %>
	                <h5> <% if !comment.user.blank? %>
										<%= comment.user.email %>
										<% end %>
	                    <small><%= comment.created_at %></small>
	                </h5>
									<p><%= comment.body %></p>
									<% end %>
									<hr>
									<% if !@vote.blank? %>
									<% if @vote.support %>
                	<div class="well">
	                	
                    <h4>Leave a Comment:</h4>
										<%= form_for([@topic, @topic.comments.build]) do |f| %>
										  <div class="form-group">
										    <%= f.text_area :body, :class=>"form-control tags", :rows => 3 %>
										  </div>
										    <%= f.submit "Comment", :class=>"btn btn-primary" %>
										<% end %>
										
                	</div>
									<% end %>
									<% end %>
                	

                	
								</div>
								
								<div class="col-lg-6">
                	
									<h4>Against Comments</h4>
									<hr>
									<% @against_comments.each do |comment| %>
	                <h5> <% if !comment.user.blank? %>
										<%= comment.user.email %>
										<% end %>
	                    <small><%= comment.created_at %></small>
	                </h5>
									<p><%= comment.body %></p>
									<% end %>
									<hr>
									<% if !@vote.blank? %>
									<% if !@vote.support %>
                	<div class="well">
                    <h4>Leave a Comment:</h4>
										<%= form_for([@topic, @topic.comments.build]) do |f| %>
										  <div class="form-group">
										    <%= f.text_area :body, :class=>"form-control", :rows => 3 %>
										  </div>
										    <%= f.submit "Comment", :class=>"btn btn-primary" %>
										<% end %>
										
                	</div>
									<% end %>
									<% end %>
                	
								</div>
									
										
 </div>
 
 <script type="text/javascript">
 var availableTags = [
     "ActionScript",
     "AppleScript",
     "Asp",
     "BASIC",
     "C",
     "C++",
     "Clojure",
     "COBOL",
     "ColdFusion",
     "Erlang",
     "Fortran",
     "Groovy",
     "Haskell",
     "Java",
     "JavaScript",
     "Lisp",
     "Perl",
     "PHP",
     "Python",
     "Ruby",
     "Scala",
     "Scheme"
     ];

 function split(val) {
     return val.split(/@\s*/);
 }

 function extractLast(term) {
     return split(term).pop();
 }

 $(".tags")
 // don't navigate away from the field on tab when selecting an item
 .bind("keydown", function(event) {
     if (event.keyCode === $.ui.keyCode.TAB && $(this).data("autocomplete").menu.active) {
         event.preventDefault();
     }
 }).autocomplete({
     minLength: 0,
     source: function(request, response) {
         var term = request.term,
             results = [];
         if (term.indexOf("@") >= 0) {
             term = extractLast(request.term);
             if (term.length > 0) {
                 results = $.ui.autocomplete.filter(
                 availableTags, term);
             } else {
                 results = ['Start typing...'];
             }
         }
         response(results);
     },
     focus: function() {
         // prevent value inserted on focus
         return false;
     },
     select: function(event, ui) {
         var terms = split(this.value);
         // remove the current input
         terms.pop();
         // add the selected item
         terms.push(ui.item.value);
         // add placeholder to get the comma-and-space at the end
         terms.push("");
         this.value = terms.join("");
         return false;
     }
 });
 </script>